version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: phoenix!1688
      MYSQL_DATABASE: andon
      MYSQL_USER: cvazquez
      MYSQL_PASSWORD: Sonnys2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    #- ./init-mysql.sh:/docker-entrypoint-initdb.d/init-mysql.sh

    #command: --default-authentication-plugin=mysql_native_password


  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "5005:5005"
    depends_on:
      - db
        
    environment:
      - TZ=America/New_York
      - FLASK_ENV=production
      - SECRET_KEY=wCDyL:tM$zorB[>g8/l|:C2YeUJScrb"7dBRdfi)aA3{~+L#HPpBJDBd;3Q7/Ni
      - DB_USER=cvazquez
      - DB_PASSWORD=Sonnys2024
      - DB_HOST=db
      - DB_NAME=andon
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=SonnysAndon2024

volumes:
  db_data:
