"""Add notified field to Ticket

Revision ID: 07b004b3ee3a
Revises: e0f1906356c8
Create Date: 2024-06-24 13:01:23.061828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b004b3ee3a'
down_revision = 'e0f1906356c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_ticket', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ticket_id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('notified')

    with op.batch_alter_table('closed_ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
